name: Automerge-PR
on:
  pull_request_target:
      types:
        - opened
        - labeled
        - unlabeled
        - ready_for_review

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          merge-method: squash
          do-not-merge-labels: never-merge
          required-labels: automerge
          pull-request: ${{ github.event.inputs.pull-request }}